### ISSUE TITLE
Add on_connect_do support.

### ISSUE THREAD

**Issue by bluefeet** [theory/dbix-connector#42]
I've create a subclass of DBIx::Connector which supports OnConnectDo in the DBI options hash ref.  It works very well and I'd like to move it out of @work code and into DBIx::Connector.  Is this something you'd be OK with receiving a pull request on?  Just want to make sure before I make the effort.

**Comment by theory** [comment]
What is OnConnectDo?

**Comment by theory** [comment]
That's what [DBI Callbacks](http://search.cpan.org/~timb/DBI-1.632/DBI.pm#Callbacks) are for. Do this instead:

    my $conn = DBIx::Connector->new($dsn, $user, $pass, {
        AutoCommit => 1,
        Callbacks => { connected => sub {
            shift->do(q[SET SESSION sql_mode = 'TRADITIONAL']);
            return;
         } },
    );

**Comment by bluefeet** [comment]
Crap, can't believe I missed that.  Thanks.

**Comment by theory** [comment]
It's shocking how often this has come up. I even added a pointer to `Callbacks` to the DBIx::Connector docs to try to reduce the support overhead. :-)

**Comment by bluefeet** [comment]
And I missed that to???  /me hangs head in shame
Thanks, dude.  :)

**Comment by theory** [comment]
Well, it is just a [single sentence](https://github.com/theory/dbix-connector/blob/master/lib/DBIx/Connector.pm#L636).
